---
takel_ship_scripts_scripts_scripts:
  - "{{ takel_ship_scripts_script_cli }}"
  - "{{ takel_ship_scripts_script_cmd }}"

### end of group_vars

# default vars for role unit test
takel_ship_scripts:
  - "{{ takel_ship_scripts_script_cli }}"
  - "{{ takel_ship_scripts_script_cmd }}"

takel_ship_scripts_script_cli:
  name: cli
  role: takel_ship_scripts
  template: cli.bash.j2
  list: true

takel_ship_scripts_script_cmd:
  name: cmd
  role: takel_ship_scripts
  template: cmd.bash.j2
  list: true

takel_ship_scripts_root:
  owner: root
  group: root
  mode:
    dir: "0755"
    file: "0644"

takel_ship_scripts_dir: /usr/local/bin
takel_ship_scripts_shebang: '#!/usr/bin/env bash'
