---
takel_ship_scripts_scripts_scripts:
  - "{{ takel_ship_scripts_script_cli }}"
  - "{{ takel_ship_scripts_script_pod }}"
  - "{{ takel_ship_scripts_script_compose_nonroot }}"
  - "{{ takel_ship_scripts_script_bash_history_root }}"

### end of group_vars

# default vars for role unit test
takel_ship_scripts:
  - "{{ takel_ship_scripts_script_cli }}"
  - "{{ takel_ship_scripts_script_pod }}"
  - "{{ takel_ship_scripts_script_compose_nonroot }}"
  - "{{ takel_ship_scripts_script_bash_history_root }}"

takel_ship_scripts_script_cli:
  name: cli
  description: List available commands.
  list: true
  role: takel_ship_scripts
  template: cli.bash.j2

takel_ship_scripts_script_pod:
  name: pod
  description: "Run as {{ takel_ship_podman_user.owner }} user."
  list: true
  role: takel_ship_scripts
  template: pod.bash.j2

takel_ship_scripts_script_compose_nonroot:
  name: compose-nonroot
  description: Run nonroot podman-compose.
  role: takel_ship_scripts
  list: true
  template: compose-nonroot.bash.j2

takel_ship_scripts_script_bash_history_root:
  name: .bash_history
  role: takel_ship_scripts
  template: bash_history.root.j2
  owner: "{{ takel_ship_scripts_root.owner }}"
  group: "{{ takel_ship_scripts_root.group }}"
  mode: "{{ takel_ship_scripts_root.mode.file }}"
  path: /root

takel_ship_scripts_root:
  owner: root
  group: root
  mode:
    dir: "0755"
    file: "0644"

takel_ship_scripts_dir: /usr/local/bin
takel_ship_scripts_shebang: |
  #!/bin/bash
  DEBUG="${TAKELSHIP_DEBUG:-'false'}"
  DEBUG="${DEBUG,,}"
  [[ "$DEBUG" == "true" ]] && set -xv
