---
takelship:
  name: takelship
  docker_host: "{{ takel_ship_dind_docker_32375['port'] }}"
  default_project: "{{ takel_ship_compose_default_project }}"
  image: >-
    {{ project['images']['project']['target_user'] }}/{{
    project['images']['project']['target_repo'] }}:{{
    project['version'] }}
  projects: "{{ takel_ship_compose_projects }}"
