---
takel_ship_compose_projects:
  - name: all
    description: >-
      All services.
    services:
      - "{{ takel_ship_registry_service }}"
      - "{{ takel_ship_forgejo_service }}"
      - "{{ takel_ship_teamcity_server_service }}"
      - "{{ takel_ship_teamcity_runner_service }}"
  - name: registry
    description: >-
      Docker registry (docs.docker.com/registry).
      Provides image hosting.
    services:
      - "{{ takel_ship_registry_service }}"
  - name: forgejo
    description: >-
      Forgejo Gitea clone (forgejo.org).
      Provides image hosting.
      Provides git hosting.
      Provides CI/CD pipelines (GitHub style).
    services:
      - "{{ takel_ship_forgejo_service }}"
  - name: teamcity
    description: >-
      TeamCity build server (jetbrains.com/teamcity).
      Provides CI/CD pipelines (JetBrains style).
      Runs with Forgejo.
    services:
      - "{{ takel_ship_forgejo_service }}"
      - "{{ takel_ship_teamcity_server_service }}"
      - "{{ takel_ship_teamcity_runner_service }}"

takel_ship_compose_default_project: forgejo
