---
takel_ship_compose_projects:
  - name: all
    description: >-
      All services of all projects.
    services:
      - "{{ takel_ship_registry_server_service }}"
      - "{{ takel_ship_registry_ui_service }}"
      - "{{ takel_ship_forgejo_server_service }}"
      - "{{ takel_ship_forgejo_runner_service }}"
      - "{{ takel_ship_teamcity_server_service }}"
      - "{{ takel_ship_teamcity_runner_service }}"
  - name: registry
    description: >-
      Docker registry (distribution.github.io/distribution).
      Provides image hosting.
      Registry UI (github.com/quiq/registry-ui).
      Provides registry web interface.
    services:
      - "{{ takel_ship_registry_server_service }}"
      - "{{ takel_ship_registry_ui_service }}"
  - name: forgejo
    description: >-
      Forgejo Gitea fork (forgejo.org).
      Provides git hosting.
      Provides CI/CD pipelines (GitHub style).
      Provides image hosting.
      Runs with Forgejo Runners.
      Runs with Docker in Docker.
    services:
      - "{{ takel_ship_forgejo_server_service }}"
      - "{{ takel_ship_forgejo_runner_service }}"
  - name: teamcity
    description: >-
      TeamCity build server (jetbrains.com/teamcity).
      Provides CI/CD pipelines (JetBrains style).
      Runs with TeamCity Runners.
      Runs with Docker in Docker.
      Runs with Forgejo for git and image hosting.
    services:
      - "{{ takel_ship_dind_docker_service }}"
      - "{{ takel_ship_forgejo_server_service }}"
      - "{{ takel_ship_teamcity_server_service }}"
      - "{{ takel_ship_teamcity_runner_service }}"
