---
takel_ship_teamcity_services:
  - "{{ takel_ship_teamcity_server_service }}"
  - "{{ takel_ship_teamcity_runner_service }}"

### end of group_vars

takel_ship_teamcity_server_service:
  name: teamcity-server
  description: >-
    TeamCity build server (jetbrains.com/teamcity).
    Provides CI/CD pipelines (JetBrains style).
  role: takel_ship_teamcity
  template: docker-compose.teamcity-server.yml.j2
  env: env.teamcity-server.j2
  images:
    - "{{ takel_ship_teamcity_server_image }}"
  ports:
    - "{{ takel_ship_teamcity_server_http_38111 }}"
  profiles:
    - podman
    - docker

takel_ship_teamcity_runner_service:
  name: teamcity-runner
  description: >-
    TeamCity build server runner (jetbrains.com/teamcity).
    Provides runner for TeamCity CI/CD pipelines.
  role: takel_ship_teamcity
  template: docker-compose.teamcity-runner.yml.j2
  env: env.teamcity-runner.j2
  preinstall: run-preinstall.teamcity-runner.bash.j2
  instances: 3
  images:
    - "{{ takel_ship_teamcity_runner_amd64_image }}"
    - "{{ takel_ship_teamcity_runner_arm64_image }}"
  profiles:
    - podman
    - docker

takel_ship_teamcity_version: 2024.07.3

takel_ship_teamcity_server_image:
  name: jetbrains/teamcity-server
  tag: "{{ takel_ship_teamcity_version }}"
  alias: teamcity-server

takel_ship_teamcity_runner_amd64_image:
  name: jetbrains/teamcity-agent
  tag: "{{ takel_ship_teamcity_version }}-linux-sudo"
  alias: teamcity-agent-linux-sudo
  arch: x86_64

takel_ship_teamcity_runner_arm64_image:
  name: jetbrains/teamcity-agent
  tag: "{{ takel_ship_teamcity_version }}-linux-arm64-sudo"
  alias: teamcity-agent-linux-arm64-sudo
  arch: aarch64

takel_ship_teamcity_server_http_38111:
  port: 38111
  protocol: http

takel_ship_teamcity_restart: always
