---
takel_ship_teamcity_services:
  - "{{ takel_ship_teamcity_server_service }}"
  - "{{ takel_ship_teamcity_runner_service }}"

### end of group_vars

takel_ship_teamcity_server_service:
  name: teamcity-server
  role: takel_ship_teamcity
  template: docker-compose.teamcity-server.yml.j2
  env: env.teamcity-server.j2
  images:
    - "{{ takel_ship_teamcity_server_image }}"
  ports:
    - "{{ takel_ship_teamcity_http_port }}"
  volumes:
    - name: teamcity-data
      mount: /data/teamcity_server/datadir
    - name: teamcity-logs
      mount: /opt/teamcity/logs

takel_ship_teamcity_runner_service:
  name: teamcity-runner
  role: takel_ship_teamcity
  template: docker-compose.teamcity-runner.yml.j2
  env: env.teamcity-runner.j2
  images:
    - "{{ takel_ship_teamcity_agent_image }}"

takel_ship_teamcity_server_image:
  name: jetbrains/teamcity-server
  tag: 2024.07.2
  alias: teamcity-server

takel_ship_teamcity_agent_image:
  name: jetbrains/teamcity-agent
  tag: 2024.07.2-linux-sudo
  alias: teamcity-agent-linux-sudo

takel_ship_teamcity_http_port:
  name: http
  port: 38111

takel_ship_teamcity_restart: always

takel_ship_teamcity_agents: 3
