---
takel_pod_forgejo_service:
  name: forgejo
  role: takel_pod_forgejo
  template: docker-compose.forgejo.yml.j2
  volumes:
    - name: data
      mount: /data
  images:
    - "{{ takel_pod_forgejo_image }}"

takel_pod_forgejo_image:
  name: codeberg.org/forgejo/forgejo
  tag: 8
  alias: forgejo

takel_pod_forgejo_script_forgejo:
  name: "{{ takel_pod_forgejo_bin_cli }}"
  role: takel_pod_forgejo
  template: forgejo.bash.j2
  list: true

takel_pod_forgejo_uid: 1000
takel_pod_forgejo_gid: 1000
takel_pod_forgejo_restart: always
takel_pod_forgejo_http_port: 3000
takel_pod_forgejo_ssh_port: 22

takel_pod_forgejo_bin_cli: forgejo
takel_pod_forgejo_bin_container_command: >-
  podman exec -it forgejo forgejo
