# frozen_string_literal: true

require 'rake'

cmd_login_root = 'docker exec ' \
    '--interactive ' \
    '--tty ' \
    'molecule_default_takelbeta_takelship_%<unique>s ' \
    'bash'

cmd_login_podman = 'docker exec ' \
    '--interactive ' \
    '--tty ' \
    'molecule_default_takelbeta_takelship_%<unique>s ' \
    'cmd shell'

namespace :login do
  begin
    unique = ENV['HOSTNAME'][-11..]
  rescue StandardError
    unique = 'nonunique'
  end
  desc 'Login as root'
  task :root do
    @commands << format(
      cmd_login_root,
      unique: unique
    )
  end
  desc 'Login as podman'
  task :podman do
    @commands << format(
      cmd_login_podman,
      unique: unique
    )
  end
end
