default:
  image:
    name: takelwerk/takelbuild:latest
  services:
    - name: docker:dind
      command: [ "dockerd", "-H", "tcp://0.0.0.0:2375", "--tls=false", "--mtu=1410" ]

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ''  # unset means: "unencrypted"
  GITHUB_API_TOKEN: $GITHUB_API_TOKEN

stages:
  - build_arm64

build_arm64:
  stage: build_arm64
  only:
    - tags
  script:
    # Link project directory
    - ln -fs $CI_PROJECT_DIR /project

    # Lint ruby
    - rake rubylint

    # Update debian base image
    - rake images:project:update

    # Build image with packer
    - rake images:project:build

    # Test takelage project image
    - rake images:project:molecule:test

    # Login to dockerhub
    - docker login --username takelwerk --password $DOCKERHUB_TOKEN

    # Tag and push image
    - rake dockerhub:project:tag:latest:arm64
    - rake dockerhub:project:push:latest:arm64
    - rake dockerhub:project:tag:version:arm64
    - rake dockerhub:project:push:version:arm64

    # Create and push docker latest manifest if amd64 image exists
    - if rake dockerhub:project:pull:latest:amd64; then \
        rake dockerhub:project:manifest:create:latest; \
        rake dockerhub:project:manifest:push:latest; \
      fi

    # Create and push docker version manifest if amd64 image exists
    - if rake dockerhub:project:pull:version:amd64; then \
       rake dockerhub:project:manifest:create:version; \
       rake dockerhub:project:manifest:push:version; \
     fi
