services:
  takelship:
    #image: takelwerk/takelship
    ##################################
    ### takelage debug image
    ###
    image: packer_local/takelship-project
    ###
    ##################################
    container_name: takelship
    hostname: takelship
    ##################################
    ###
    # entrypoint: /usr/bin/tail -f /dev/null
    ###
    ### run entrypoint script manually
    ###
    ### usually you run as a single command:
    ###   $ docker compose down; \
    ###     docker compose up; \
    ###     docker compose down
    ###
    ### to debug you start it instead with:
    ###   $  docker run -it --rm --privileged \
    ###     --hostname takelship --name takelship \
    ###     --entrypoint bash \
    ###     packer_local/takelship-project:latest
    ###
    ### then inside the container you run: root@takelship:~# TAKELSHIP_DEBUG=true /entrypoint
    ###
    ##################################
    privileged: true
    environment:
      TAKELSHIP_PROJECT: default
    ### 
    #   TAKELSHIP_DEBUG: false
    ### enables debug logging to stdout
    #   TAKELSHIP_UPDATE:
    ### controls updates of compose filese in the compose dir
    ### see /home/podman/datacompose/<service>/env
    ### for service specific environment variables
    ### /home/podman/datacompose
    volumes:
      - ${TAKELSHIP_DATADIR:-./data}:/home/podman/data
    ports:
      - "35000:35000"  #  registry http
      - "30022:30022"  #  forgejo ssh
      - "33000:33000"  #  forgejo http
      - "38111:38111"  #  teamcity http
