---
- name: (install) ensure directory exists
  ansible.builtin.file:
    path: >-
      {{ takel_ship_scripts_script.path | default(takel_ship_scripts_dir) }}
    owner: >-
      {{ takel_ship_scripts_script.owner |
      default(takel_ship_scripts_root.owner) }}
    group: >-
      {{ takel_ship_scripts_script.group |
      default(takel_ship_scripts_root.group) }}
    mode: >-
      {{ takel_ship_scripts_script.createdir |
      default(takel_ship_scripts_root.mode.dir) }}
    state: directory
  loop: "{{ takel_ship_scripts_scripts }}"
  loop_control:
    loop_var: takel_ship_scripts_script
  when:
    - takel_ship_scripts_script.template is defined
    - takel_ship_scripts_script.createdir is defined

- name: (install) deploy executable file
  ansible.builtin.template:
    src: >-
      ../../{{ takel_ship_scripts_script.role }}/templates/{{
      takel_ship_scripts_script.template }}
    dest: >-
      {{ takel_ship_scripts_script.path | default(takel_ship_scripts_dir) }}/{{
      takel_ship_scripts_script.name }}
    owner: >-
      {{ takel_ship_scripts_script.owner |
      default(takel_ship_scripts_root.owner) }}
    group: >-
      {{ takel_ship_scripts_script.group |
      default(takel_ship_scripts_root.group) }}
    # we use default(takel_ship_scripts_root.mode.dir)
    # as the file should be executable
    mode: >-
      {{ takel_ship_scripts_script.mode |
      default(takel_ship_scripts_root.mode.dir) }}
  loop: "{{ takel_ship_scripts_scripts }}"
  loop_control:
    loop_var: takel_ship_scripts_script
  when: takel_ship_scripts_script.template is defined
