---
name: takelship

on:
  push:
  workflow_dispatch:

env:
  HOMEDIR: /tmp/act/job-${{ github.run_id }}
  PROJECTDIR: ${{ env.HOMEDIR }}/project

jobs:
  takelship:
    container:
      image: takelwerk/takelbuild
      options: "--hostname job-${{ github.run_id }} --tty"
      volumes:
        - act:/tmp/act
    steps:
      - name: Prepare docker socket
        run: chgrp docker /var/run/docker.sock

      - name: Check out repository
        run: git clone http://forgejo-server:3000/takelwerk/takelship.git /$RUNNER_TEMP/checkout

      - name: Add takelbuild user
        run: useradd --create-home --home-dir $HOMEDIR --user-group takelbuild --groups docker

      - name: Copy repository
        run: su takelbuild -c "rsync --archive /$RUNNER_TEMP/checkout/ $PROJECTDIR"

      - name: Link project directory
        run: ln -s $PROJECTDIR /project

      - name: Lint ruby
        run: su takelbuild -c "cd $PROJECTDIR && rake rubylint"

      - name: Lint project
        run: su takelbuild -c "cd $PROJECTDIR && rake images:project:registry:molecule:lint"

      - name: Interrupt workflow
        run: |
          echo Delete /$RUNNER_TEMP/delete_me_to_continue_workflow to continue workflow
          su takelbuild -c "touch /$RUNNER_TEMP/delete_me_to_continue_workflow"
          while [ -f /$RUNNER_TEMP/delete_me_to_continue_workflow ]; do sleep 1; done

      - name: Build takelage project image with packer
        run: su takelbuild -c "cd $PROJECTDIR && rake images:project:build"

      - name: Test takelship project registry
        run: su takelbuild -c "cd $PROJECTDIR && rake images:project:registry:molecule:test"

      - name: Test takelship project forgejo
        run: su takelbuild -c "cd $PROJECTDIR && rake images:project:forgejo:molecule:test"
