---
name: takelship

on:
  push:
  workflow_dispatch:

env:
  WORKDIR=/tmp/act/task-$GITHUB_RUN_NUMBER
  PROJECTDIR=$WORKDIR/project

jobs:
  takelship:
    runs-on: takelbuild
    container:
      volumes:
        - /tmp/act:/tmp/act
    steps:
      - name: Check out repository
        run: git clone http://forgejo-server:3000/takelwerk/takelship.git /$RUNNER_TEMP/checkout

      - name: Add takelbuild user
        run: useradd --create-home --home-dir $HOMEDIR --user-group takelbuild

      - name: Copy repository
        run: |
          mkdir $HOMEDIR/project
          rsync -a /$RUNNER_TEMP/checkout/ $PROJECTDIR

      - name: Link project directory
        run: ln -s $PROJECTDIR /project

      - name: Become takelbuild
        run: |
          su - takelbuild
          cd $PROJECTDIR

      - name: Lint ruby
        run: rake rubylint

      - name: Lint project
        run: rake images:project:registry:molecule:lint

      - name: Interrupt workflow
        run: |
          touch /$RUNNER_TEMP/delete_me_to_continue_workflow
          while [ -f /$RUNNER_TEMP/delete_me_to_continue_workflow ]; do sleep 1; done

      - name: Build takelage project image with packer
        run: rake images:project:build

      - name: Test takelship project registry
        run: rake images:project:registry:molecule:test

      - name: Test takelship project forgejo
        run: rake images:project:forgejo:molecule:test
