---
takel_ship_aptproxy_services:
  - "{{ takel_ship_aptproxy_server_service }}"

### end of group_vars

takel_ship_aptproxy_server_service:
  name: aptproxy-server
  description: >-
    APT Proxy (github.com/soulteary/apt-proxy)
    Provides apt caching.
  role: takel_ship_aptproxy
  template: docker-compose.aptproxy-server.yml.j2
  env: env.aptproxy-server.j2
  images:
    - "{{ takel_ship_aptproxy_server_image }}"
  ports:
    - "{{ takel_ship_aptproxy_server_http_33142 }}"
  profiles:
    - podman
    - docker
takel_ship_aptproxy_server_image:
  name: docker.io/soulteary/apt-proxy
  tag: latest

takel_ship_aptproxy_server_http_33142:
  port: 33142
  protocol: http
