---
- name: (main) include upgrade
  ansible.builtin.include_tasks: upgrade.yml
  tags: always

- name: (main) include install
  ansible.builtin.include_tasks: install.yml
  tags: always

- name: (main) include user
  ansible.builtin.include_tasks: user.yml
  tags: always
