---
takel_ship_forgejo_services:
  - "{{ takel_ship_forgejo_service }}"

takel_ship_forgejo_scripts:
  - "{{ takel_ship_forgejo_script_forgejo }}"

### end of group_vars

takel_ship_forgejo_service:
  name: forgejo
  role: takel_ship_forgejo
  template: docker-compose.forgejo.yml.j2
  env: env.forgejo.j2
  volumes:
    - name: data
      mount: /data
  images:
    - "{{ takel_ship_forgejo_image }}"

takel_ship_forgejo_image:
  name: codeberg.org/forgejo/forgejo
  tag: 8
  alias: forgejo

takel_ship_forgejo_script_forgejo:
  name: "{{ takel_ship_forgejo_bin_cli }}"
  role: takel_ship_forgejo
  template: forgejo.bash.j2
  list: true

takel_ship_forgejo_uid: 1000
takel_ship_forgejo_gid: 1000
takel_ship_forgejo_restart: always
takel_ship_forgejo_http_port: 33000
takel_ship_forgejo_ssh_port: 30022

takel_ship_forgejo_bin_cli: forgejo
takel_ship_forgejo_bin_container_command: >-
  podman exec -it forgejo forgejo
