---
takel_ship_forgejo_services:
  - "{{ takel_ship_forgejo_server_service }}"
  - "{{ takel_ship_forgejo_runner_service }}"

takel_ship_forgejo_scripts:
  - "{{ takel_ship_forgejo_script_forgejo }}"
  - "{{ takel_ship_forgejo_script_tea_config }}"
  - "{{ takel_ship_forgejo_script_fortea_add_ssh_key }}"
  - "{{ takel_ship_forgejo_script_fortea_generate_ssh_key }}"
  - "{{ takel_ship_forgejo_script_runner_config }}"

### end of group_vars

takel_ship_forgejo_deb_install_packages:
  - tea-cli

takel_ship_forgejo_server_service:
  name: forgejo-server
  description: >-
    Forgejo Gitea fork (forgejo.org).
    Provides git hosting.
    Provides CI/CD pipelines (GitHub style).
    Provides image hosting.
  role: takel_ship_forgejo
  template: docker-compose.forgejo-server.yml.j2
  env: env.forgejo-server.j2
  preinstall: run-preinstall.forgejo-server.bash.j2
  postinstall: run-postinstall.forgejo-server.bash.j2
  nonroot: true
  images:
    - "{{ takel_ship_forgejo_server_image }}"
  ports:
    - "{{ takel_ship_forgejo_server_http_33000 }}"
    - "{{ takel_ship_forgejo_server_ssh_30022 }}"
  profiles:
    - podman
    - docker

takel_ship_forgejo_runner_service:
  name: forgejo-runner
  description: >-
    Forgejo Gitea fork runner (forgejo.org).
    Provides runner for Forgejo CI/CD pipelines.
  role: takel_ship_forgejo
  template: docker-compose.forgejo-runner.yml.j2
  env: env.forgejo-runner.j2
  preinstall: run-postinstall.forgejo-runner.bash.j2
  nonroot: true
  instances: 3
  images:
    - "{{ takel_ship_forgejo_runner_image }}"
  profiles:
    - podman
    - docker

takelship_forgejo_runner_labels:
  - debian:docker://docker.io/node:20-bookworm
  - ubuntu:docker://ghcr.io/catthehacker/ubuntu:runner-latest
  - ubuntu-root:docker://ghcr.io/catthehacker/ubuntu:act-latest
  - ubuntu-full:docker://ghcr.io/catthehacker/ubuntu:full-latest

takel_ship_forgejo_server_image:
  name: codeberg.org/forgejo/forgejo
  tag: 8-rootless

takel_ship_forgejo_runner_image:
  name: code.forgejo.org/forgejo/runner
  tag: 3.5.1

takel_ship_forgejo_script_forgejo:
  name: "{{ takel_ship_forgejo_bin_cli }}"
  description: Forgejo admin command line interface.
  list: true
  role: takel_ship_forgejo
  template: forgejo.bash.j2

takel_ship_forgejo_script_tea_config:
  name: config.yml
  role: takel_ship_forgejo
  template: tea.config.yml.j2
  owner: "{{ takel_ship_podman_user.owner }}"
  group: "{{ takel_ship_podman_user.group }}"
  mode: "{{ takel_ship_podman_user.mode.file }}"
  createdir: "{{ takel_ship_podman_user.mode.dir }}"
  path: >-
    {{ takel_ship_compose_home_dir
    }}/.config/tea

takel_ship_forgejo_script_fortea_add_ssh_key:
  name: fortea-add-ssh-key
  description: Add ssh key to forgejo server admin account.
  list: true
  role: takel_ship_forgejo
  template: fortea-add-ssh-key.bash.j2

takel_ship_forgejo_script_fortea_generate_ssh_key:
  name: fortea-generate-ssh-key
  description: Generate an ssh key pair for the forgejo server admin account.
  role: takel_ship_forgejo
  template: fortea-generate-ssh-key.bash.j2

takel_ship_forgejo_script_runner_config:
  name: config.yml
  role: takel_ship_forgejo
  template: runner.config.yml.j2
  owner: "{{ takel_ship_podman_user.owner }}"
  group: "{{ takel_ship_podman_user.group }}"
  mode: "{{ takel_ship_podman_user.mode.file }}"
  createdir: "{{ takel_ship_podman_user.mode.dir }}"
  path: >-
    {{ takel_ship_compose_home_dir }}/{{
    takel_ship_compose_dist_dir }}/{{
    takel_ship_compose_compose_dir }}/{{
    takel_ship_compose_services_dir }}/{{
    takel_ship_forgejo_runner_service.name }}

takel_ship_forgejo_server_ssh_30022:
  port: 30022
  protocol: ssh

takel_ship_forgejo_server_http_33000:
  port: 33000
  protocol: http
  description: administrator/administrator

takel_ship_forgejo_uid: 1000
takel_ship_forgejo_gid: 1000

takel_ship_forgejo_bin_cli: forgejo

takel_ship_forgejo_admin:
  name: administrator
  password: administrator
  email: administrator@example.com

takel_ship_forgejo_server_ssh_key:
  private_key_file: >-
    {{ takel_ship_compose_home_dir }}/{{
    takel_ship_compose_data_dir }}/{{
    takel_ship_compose_compose_dir }}/{{
    takel_ship_compose_services_dir }}/{{
    takel_ship_forgejo_server_service.name
    }}/id_ed25519.administrator
  public_key_file: >-
    {{ takel_ship_compose_home_dir }}/{{
    takel_ship_compose_data_dir }}/{{
    takel_ship_compose_compose_dir }}/{{
    takel_ship_compose_services_dir }}/{{
    takel_ship_forgejo_server_service.name
    }}/id_ed25519.administrator.pub

# -C '' = no comment
# -N '' = no password
# -f <file> = private key file name
takel_ship_forgejo_server_ssh_keygen: >-
  ssh-keygen -C '' -N '' -f {{
  takel_ship_forgejo_server_ssh_key.private_key_file }}

takelship_forgejo_runner_secret: >-
  7c31591e8b67225a116d4a4519ea8e507e08f71f
takelship_forgejo_runner_command_register: >-
  "while : ; do sleep 1 ; done ;"
takelship_forgejo_runner_command_daemon: >-
  "sleep 5; forgejo-runner daemon --config /config.yml"
