---
takel_ship_forgejo_services:
  - "{{ takel_ship_forgejo_server_service }}"
  - "{{ takel_ship_forgejo_runner_service }}"
  - "{{ takel_ship_forgejo_dind_service }}"

takel_ship_forgejo_scripts:
  - "{{ takel_ship_forgejo_script_forgejo }}"
  - "{{ takel_ship_forgejo_script_tea_config }}"

### end of group_vars

takel_ship_forgejo_deb_install_packages:
  - tea-cli

takel_ship_forgejo_server_service:
  name: forgejo-server
  description: >-
    Forgejo Gitea fork (forgejo.org).
    Provides git hosting.
    Provides CI/CD pipelines (GitHub style).
    Provides image hosting.
  role: takel_ship_forgejo
  template: docker-compose.forgejo-server.yml.j2
  env: env.forgejo-server.j2
  preinstall: run-preinstall.forgejo-server.bash.j2
  postinstall: run-postinstall.forgejo-server.bash.j2
  nonroot: true
  images:
    - "{{ takel_ship_forgejo_server_image }}"
  ports:
    - "{{ takel_ship_forgejo_server_http_33000 }}"
    - "{{ takel_ship_forgejo_server_ssh_30022 }}"
  profiles:
    - podman
    - docker

takel_ship_forgejo_runner_service:
  name: forgejo-runner
  description: >-
    Forgejo Gitea fork runner (forgejo.org).
    Provides runner for Forgejo CI/CD pipelines.
  role: takel_ship_forgejo
  template: docker-compose.forgejo-runner.yml.j2
  env: env.forgejo-runner.j2
  preinstall: run-postinstall.forgejo-runner.bash.j2
  nonroot: true
  instances: 3
  dind: 2330
  images:
    - "{{ takel_ship_forgejo_runner_image }}"
  profiles:
    - podman
    - docker

takel_ship_forgejo_dind_service:
  name: forgejo-dind
  description: >-
    Forgejo Gitea fork docker in docker (forgejo.org).
    Provides Docker in Docker for Forgejo runner
  role: takel_ship_forgejo
  template: docker-compose.forgejo-dind.yml.j2
  env: env.forgejo-dind.j2
  instances: 3
  dind: 2330
  profiles:
    - docker

takel_ship_forgejo_server_image:
  name: codeberg.org/forgejo/forgejo
  tag: 8-rootless
  alias: forgejo

takel_ship_forgejo_runner_image:
  name: code.forgejo.org/forgejo/runner
  tag: 3.5.1
  alias: runner

takel_ship_forgejo_dind_image:
  name: code.forgejo.org/oci/docker
  tag: dind

takel_ship_forgejo_script_forgejo:
  name: "{{ takel_ship_forgejo_bin_cli }}"
  description: Forgejo admin command line interface.
  list: true
  role: takel_ship_forgejo
  template: forgejo.bash.j2

takel_ship_forgejo_script_tea_config:
  name: config.yml
  role: takel_ship_forgejo
  template: tea.config.yml.j2
  owner: "{{ takel_ship_podman_user.owner }}"
  group: "{{ takel_ship_podman_user.group }}"
  mode: "{{ takel_ship_podman_user.mode.file }}"
  createdir: "{{ takel_ship_podman_user.mode.dir }}"
  path: >-
    {{ takel_ship_compose_home_dir
    }}/.config/tea

takel_ship_forgejo_server_ssh_30022:
  port: 30022
  protocol: ssh

takel_ship_forgejo_server_http_33000:
  port: 33000
  protocol: http
  description: administrator/administrator

takel_ship_forgejo_uid: 1000
takel_ship_forgejo_gid: 1000

takel_ship_forgejo_bin_cli: forgejo

takel_ship_forgejo_admin:
  name: administrator
  password: administrator
  email: administrator@example.com

takelship_forgejo_runner_secret: >-
  7c31591e8b67225a116d4a4519ea8e507e08f71f
takelship_forgejo_runner_labels:
  - "debian:docker://node:20-bookworm"
  - "ubuntu:docker://ghcr.io/catthehacker/ubuntu:act-22.04"
  - "takelbuild:docker://takelwerk/takelbuild"
takelship_forgejo_runner_command_register: >-
  "while : ; do sleep 1 ; done ;"
takelship_forgejo_runner_command_daemon: >-
  "sleep 5; forgejo-runner daemon"
