---
takel_ship_forgejo_services:
  - "{{ takel_ship_forgejo_server_service }}"
  - "{{ takel_ship_forgejo_runner_service }}"

takel_ship_forgejo_scripts:
  - "{{ takel_ship_forgejo_script_forgejo }}"
  - "{{ takel_ship_forgejo_script_fortea }}"

### end of group_vars

takel_ship_forgejo_deb_install_packages:
  - tea-cli

takel_ship_forgejo_server_service:
  name: forgejo-server
  role: takel_ship_forgejo
  template: docker-compose.forgejo-server.yml.j2
  env: env.forgejo-server.j2
  envvar: TAKELSHIP_SERVICE_FORGEJO_SERVER
  postinstall: run-postinstall.forgejo-server.bash.j2
  images:
    - "{{ takel_ship_forgejo_server_image }}"
  ports:
    - "{{ takel_ship_forgejo_server_ssh_port }}"
    - "{{ takel_ship_forgejo_server_http_port }}"
  volumes:
    - name: data
      mount: /data

takel_ship_forgejo_runner_service:
  name: forgejo-runner
  role: takel_ship_forgejo
  template: docker-compose.forgejo-runner.yml.j2
  env: env.forgejo-runner.j2
  envvar: TAKELSHIP_SERVICE_FORGEJO_RUNNER
  preinstall: run-postinstall.forgejo-runner.bash.j2
  nonroot: true
  instances: 3
  dind: 2330
  images:
    - "{{ takel_ship_forgejo_runner_image }}"
  volumes:
    - name: data
      mount: /data

takel_ship_forgejo_server_image:
  name: codeberg.org/forgejo/forgejo
  tag: 8
  alias: forgejo

takel_ship_forgejo_runner_image:
  name: code.forgejo.org/forgejo/runner
  tag: 3.5.1
  alias: runner

takel_ship_forgejo_script_forgejo:
  name: "{{ takel_ship_forgejo_bin_cli }}"
  description: Forgejo admin command line interface.
  list: true
  role: takel_ship_forgejo
  template: forgejo.bash.j2

takel_ship_forgejo_server_ssh_port:
  port: 30022
  protocol: ssh

takel_ship_forgejo_server_http_port:
  port: 33000
  protocol: http

takel_ship_forgejo_server_root_url: >-
  http://localhost:{{ takel_ship_forgejo_server_http_port.port }}

takel_ship_forgejo_uid: 1000
takel_ship_forgejo_gid: 1000

takel_ship_forgejo_bin_cli: forgejo

takel_ship_forgejo_admin:
  name: administrator
  password: administrator
  email: administrator@example.com

takelship_forgejo_runner_secret: >-
  7c31591e8b67225a116d4a4519ea8e507e08f71f
takelship_forgejo_runner_labels: docker
takelship_forgejo_runner_command_register: >-
  "while : ; do sleep 1 ; done ;"
takelship_forgejo_runner_command_daemon: >-
  "sleep 5; forgejo-runner daemon"
takel_ship_forgejo_fortea_login: >-
  {{ takel_ship_compose_home_dir }}/{{
  takel_ship_compose_data_dir }}/{{
  takel_ship_compose_compose_dir }}/{{
  takel_ship_forgejo_server_service.name
  }}/fortea-login
