---
takel_ship_forgejo_services:
  - "{{ takel_ship_forgejo_server_service }}"
  - "{{ takel_ship_forgejo_runner_service }}"

takel_ship_forgejo_scripts:
  - "{{ takel_ship_forgejo_script_forgejo }}"

### end of group_vars

takel_ship_forgejo_server_service:
  name: forgejo-server
  role: takel_ship_forgejo
  template: docker-compose.forgejo-server.yml.j2
  env: env.forgejo-server.j2
  images:
    - "{{ takel_ship_forgejo_server_image }}"
  ports:
    - "{{ takel_ship_forgejo_server_ssh_port }}"
    - "{{ takel_ship_forgejo_server_http_port }}"
  volumes:
    - name: data
      mount: /data

takel_ship_forgejo_runner_service:
  name: forgejo-runner
  role: takel_ship_forgejo
  template: docker-compose.forgejo-runner.yml.j2
  env: env.forgejo-runner.j2
  images:
    - "{{ takel_ship_forgejo_runner_image }}"

takel_ship_forgejo_server_image:
  name: codeberg.org/forgejo/forgejo
  tag: 8
  alias: forgejo

takel_ship_forgejo_runner_image:
  name: code.forgejo.org/forgejo/runner
  tag: 3.5.1
  alias: runner

takel_ship_forgejo_script_forgejo:
  name: "{{ takel_ship_forgejo_bin_cli }}"
  role: takel_ship_forgejo
  template: forgejo.bash.j2
  list: true

takel_ship_forgejo_server_ssh_port:
  port: 30022
  protocol: ssh

takel_ship_forgejo_server_http_port:
  port: 33000
  protocol: http

takel_ship_forgejo_uid: 1000
takel_ship_forgejo_gid: 1000

takel_ship_forgejo_bin_cli: forgejo
