---
- name: (images) download internal images
  ansible.builtin.shell:
    cmd: >-
      mount / --make-rshare;
      su {{ user }} -c
      "podman image exists {{ item.name }}:{{ item.tag }}
      || podman pull {{ item.name }}:{{ item.tag }}"
    chdir: "{{ takel_ship_compose_home_dir }}"
  loop: "{{ takel_ship_registry_images }}"
  vars:
    user: "{{ takel_ship_podman_user.owner }}"
  changed_when: false
