---
- name: (images) download internal images
  ansible.builtin.shell:
    cmd: >-
      mount / --make-rshare;
      su {{ user }} -c
      "podman image exists {{ item.name }}:{{ item.tag }}
      || podman pull {{ item.name }}:{{ item.tag }}"
    chdir: "{{ takel_ship_compose_home_dir }}"
  loop: "{{ takel_ship_registry_takelship_images }}"
  vars:
    user: "{{ takel_ship_podman_user.owner }}"
  changed_when: false

- name: (images) sync images with registry
  ansible.builtin.cron:
    name: sync images
    minute: "*/5"
    user: podman
    job: >-
      {{ takel_ship_scripts_dir }}/{{
      takel_ship_registry_images_sync.name
      }} >/dev/null 2>&1
