---
- name: (compose) (projects) deploy compose file
  ansible.builtin.template:
    src: templates/docker-compose.projects.yml.j2
    dest: >-
      {{ takel_ship_services_home_dir }}/{{
      takel_ship_services_dist_dir }}/{{
      takel_ship_services_compose_dir }}/{{
      takel_ship_services_service_filename }}-{{
      takel_ship_services_project.name }}.{{
      takel_ship_services_service_fileext }}
    owner: "{{ takel_ship_services_user.owner }}"
    group: "{{ takel_ship_services_user.group }}"
    mode: '0644'
  loop: "{{ takel_ship_services_projects }}"
  loop_control:
    loop_var: takel_ship_services_project

- name: (compose) (projects) create bash run script
  ansible.builtin.template:
    src: templates/run.bash.j2
    dest: >-
      {{ takel_ship_services_home_dir }}/{{
      takel_ship_services_dist_dir }}/{{
      takel_ship_services_compose_dir
      }}/run.{{ takel_ship_services_project.name }}
    owner: "{{ takel_ship_services_user.owner }}"
    group: "{{ takel_ship_services_user.group }}"
    mode: '0755'
  loop: "{{ takel_ship_services_projects }}"
  loop_control:
    loop_var: takel_ship_services_project
