---
takel_ship_registry_services:
  - "{{ takel_ship_registry_server_service }}"
  - "{{ takel_ship_registry_ui_service }}"
  - "{{ takel_ship_registry_takelship_registry_service }}"

takel_ship_registry_scripts:
  - "{{ takel_ship_registry_script_registries }}"
  - "{{ takel_ship_registry_ui_script_config }}"
  - "{{ takel_ship_registry_server_script_config }}"
  - "{{ takel_ship_registry_images_list }}"
  - "{{ takel_ship_registry_images_push }}"
  - "{{ takel_ship_registry_images_pull }}"
  - "{{ takel_ship_registry_images_sync }}"
  - "{{ takel_ship_registry_remove_image }}"

### end of group_vars

takel_ship_registry_server_image:
  name: docker.io/library/registry
  tag: 2

takel_ship_registry_ui_image:
  name: docker.io/quiq/registry-ui
  tag: latest

# these images will pulled in the container
# the registry image is necessary
# but refrain from adding more images!
takel_ship_registry_takelship_images:
  - "{{ takel_ship_registry_server_image }}"

takel_ship_registry_server_service:
  name: registry-server
  description: >-
    Docker registry (distribution.github.io/distribution).
    Provides image hosting.
  role: takel_ship_registry
  template: docker-compose.registry-server.yml.j2
  env: env.registry-server.j2
  images:
    - "{{ takel_ship_registry_server_image }}"
  ports:
    - "{{ takel_ship_registry_server_http_35000 }}"
  profiles:
    - podman
    - docker

takel_ship_registry_ui_service:
  name: registry-ui
  description: >-
    Registry UI (github.com/quiq/registry-ui).
    Provides Socker registry web interface.
  role: takel_ship_registry
  template: docker-compose.registry-ui.yml.j2
  env: env.registry-ui.j2
  images:
    - "{{ takel_ship_registry_ui_image }}"
  ports:
    - "{{ takel_ship_registry_ui_http_35080 }}"
  profiles:
    - podman
    - docker

takel_ship_registry_takelship_registry_service:
  name: takelship-registry
  description: >-
    Docker registry (distribution.github.io/distribution).
    Provides internal takelship image hosting.
  role: takel_ship_registry
  template: docker-compose.takelship-registry.yml.j2
  env: env.takelship-registry.j2
  ports:
    - "{{ takel_ship_registry_takelship_registry_http_5555 }}"
  profiles:
    - podman
    - docker

takel_ship_registry_ui_script_config:
  name: config.yml
  role: takel_ship_registry
  template: config.registry-ui.yml.j2
  owner: "{{ takel_ship_podman_user.owner }}"
  group: "{{ takel_ship_podman_user.group }}"
  mode: "{{ takel_ship_podman_user.mode.file }}"
  path: >-
    {{ takel_ship_compose_home_dir }}/{{
    takel_ship_compose_dist_dir }}/{{
    takel_ship_compose_compose_dir }}/{{
    takel_ship_compose_services_dir }}/{{
    takel_ship_registry_ui_service.name
    }}

takel_ship_registry_server_script_config:
  name: config.yml
  role: takel_ship_registry
  template: config.registry-server.yml.j2
  owner: "{{ takel_ship_podman_user.owner }}"
  group: "{{ takel_ship_podman_user.group }}"
  mode: "{{ takel_ship_podman_user.mode.file }}"
  path: >-
    {{ takel_ship_compose_home_dir }}/{{
    takel_ship_compose_dist_dir }}/{{
    takel_ship_compose_compose_dir }}/{{
    takel_ship_compose_services_dir }}/{{
    takel_ship_registry_server_service.name
    }}

takel_ship_registry_script_registries:
  name: registries.conf
  role: takel_ship_registry
  template: registries.conf.j2
  owner: "{{ takel_ship_podman_user.owner }}"
  group: "{{ takel_ship_podman_user.group }}"
  mode: "{{ takel_ship_podman_user.mode.file }}"
  path: >-
    {{ takel_ship_compose_home_dir
    }}/.config/containers

takel_ship_registry_images_list:
  name: takelship_images_list
  role: takel_ship_registry
  template: takelship_images_list.bash.j2

takel_ship_registry_images_push:
  name: takelship_images_push
  role: takel_ship_registry
  template: takelship_images_push.bash.j2

takel_ship_registry_images_pull:
  name: takelship_images_pull
  role: takel_ship_registry
  template: takelship_images_pull.bash.j2

takel_ship_registry_images_sync:
  name: takelship_images_sync
  role: takel_ship_registry
  template: takelship_images_sync.bash.j2

takel_ship_registry_remove_image:
  name: takelship_remove_image
  role: takel_ship_registry
  template: takelship_remove_image.bash.j2

takel_ship_registry_restart: always

takel_ship_registry_to_cache_dir: ../../..
takel_ship_registry_cache_dir: cache

takel_ship_registry_takelship_registry_http_5555:
  port: 5555
  protocol: http

takel_ship_registry_server_http_35000:
  port: 35000
  protocol: http

takel_ship_registry_ui_http_35080:
  port: 35080
  protocol: http
