---
takel_ship_registry_services:
  - "{{ takel_ship_registry_service }}"
  - "{{ takel_ship_registry_takelship_service }}"

takel_ship_registry_scripts:
  - "{{ takel_ship_registry_script_registries }}"

### end of group_vars

takel_ship_registry_image:
  name: docker.io/library/registry
  tag: 2
  alias: registry

# these images will pulled in the container
# the registry image is necessary
# but refrain from adding more images!
takel_ship_registry_images:
  - "{{ takel_ship_registry_image }}"

takel_ship_registry_takelship_service:
  name: takelship-registry
  role: takel_ship_registry
  template: docker-compose.takelship-registry.yml.j2
  env: env.takelship-registry.j2
  images:
    - "{{ takel_ship_registry_image }}"
  ports:
    - "{{ takel_ship_registry_takelship_registry_port }}"
  volumes:
    - name: data
      mount: ../../cache

takel_ship_registry_service:
  name: registry
  role: takel_ship_registry
  template: docker-compose.registry.yml.j2
  env: env.registry.j2
  ports:
    - "{{ takel_ship_registry_http_port }}"
  volumes:
    - name: data
      mount: /data

takel_ship_registry_script_registries:
  name: registries.conf
  role: takel_ship_registry
  template: registries.conf.j2
  owner: "{{ takel_ship_podman_user.owner }}"
  group: "{{ takel_ship_podman_user.group }}"
  mode: "{{ takel_ship_podman_user.mode.file }}"
  path: >-
    {{ takel_ship_compose_home_dir
    }}/.config/containers

takel_ship_registry_restart: always

takel_ship_registry_cache_dir: cache

takel_ship_registry_takelship_registry_port:
  port: 5555
  protocol: http

takel_ship_registry_http_port:
  port: 35000
  protocol: http
