---
takel_ship_registry_service:
  name: registry
  role: takel_ship_registry
  template: docker-compose.registry.yml.j2
  volumes:
    - name: data
      mount: /data

takel_ship_registry_image:
  name: docker.io/library/registry
  tag: 2
  alias: registry

takel_ship_registry_images:
  - "{{ takel_ship_registry_image }}"

takel_ship_registry_script_registries:
  name: registries.conf
  role: takel_ship_registry
  template: registries.conf.j2
  owner: "{{ takel_ship_services_user.owner }}"
  group: "{{ takel_ship_services_user.group }}"
  mode: '0644'
  path: >-
    {{ takel_ship_services_home_dir
    }}/.config/containers

takel_ship_registry_script_mirror:
  name: mirror
  role: takel_ship_registry
  template: mirror.bash.j2
  owner: "{{ takel_ship_services_user.owner }}"
  group: "{{ takel_ship_services_user.group }}"
  mode: '0755'
  path: >-
    {{ takel_ship_services_home_dir }}/{{
    takel_ship_services_dist_dir }}/{{
      takel_ship_services_compose_dir }}/{{

    takel_ship_registry_service.name }}

takel_ship_registry_restart: always
takel_ship_registry_http_port: 5000
