---
- name: (compose) (services) deploy service file
  ansible.builtin.template:
    src: >-
      ../../{{ takel_ship_compose_service.role }}/templates/{{
      takel_ship_compose_service.template }}
    dest: >-
      {{ takel_ship_compose_home_dir }}/{{
      takel_ship_compose_dist_dir }}/{{
      takel_ship_compose_compose_dir }}/{{
      takel_ship_compose_service.name }}/{{
      takel_ship_compose_service_filename }}.{{
      takel_ship_compose_service_fileext }}
    owner: "{{ takel_ship_compose_user.owner }}"
    group: "{{ takel_ship_compose_user.group }}"
    mode: '0644'
  loop: "{{ takel_ship_compose_services }}"
  loop_control:
    loop_var: takel_ship_compose_service

- name: (compose) (services) deploy env file
  ansible.builtin.template:
    src: >-
      ../../{{ takel_ship_compose_service.role }}/templates/{{
      takel_ship_compose_service.env }}
    dest: >-
      {{ takel_ship_compose_home_dir }}/{{
      takel_ship_compose_dist_dir }}/{{
      takel_ship_compose_compose_dir }}/{{
      takel_ship_compose_service.name }}/env
    owner: "{{ takel_ship_compose_user.owner }}"
    group: "{{ takel_ship_compose_user.group }}"
    mode: '0644'
  loop: "{{ takel_ship_compose_services }}"
  loop_control:
    loop_var: takel_ship_compose_service
