---
takel_ship_dind_scripts:
  - "{{ takel_ship_dind_script_add_user }}"
  - "{{ takel_ship_dind_script_add_users }}"

### end of group_vars

takel_ship_dind_podman_socket:
  file: /home/podman/.run/podman.sock
  socket: unix:///home/podman/.run/podman.sock

takel_ship_dind_deb_install_packages:
  - socat

takel_ship_dind_docker_32375:
  port: 32375
  protocol: docker

takel_ship_dind_docker_socat_command: >-
  socat tcp-listen:${TAKELSHIP_DIND_DOCKER_32375:-{{
  takel_ship_dind_docker_32375['port'] }}},fork,reuseaddr
  unix-connect:/{{ takel_ship_compose_home_dir }}/.run/podman.sock

takel_ship_dind_script_add_user:
  name: takelship_dind_add_user
  description: Add system user and redirect podman socket to tcp port.
  role: takel_ship_dind
  template: takelship_dind_add_user.bash.j2

takel_ship_dind_script_add_users:
  name: takelship_dind_add_users
  description: >-
    Add dind users for projects using
    {{ takel_ship_dind_script_add_user.name }}.
  role: takel_ship_dind
  template: takelship_dind_add_users.bash.j2
