---
takel_ship_dind_services:
  - "{{ takel_ship_dind_docker_service }}"

### end of group_vars

takel_ship_dind_docker_service:
  name: docker-dind
  role: takel_ship_dind
  template: docker-compose.docker-dind.yml.j2
  env: env.docker-dind.j2
  envvar: TAKELSHIP_SERVICE_DOCKER
  images:
    - "{{ takel_ship_dind_docker_image }}"
  ports:
    - "{{ takel_ship_dind_docker_port }}"

takel_ship_dind_docker_image:
  name: alpine/socat
  tag: latest
  alias: socat

takel_ship_dind_docker_port:
  port: 32375
  protocol: docker

takel_ship_dind_command:
  tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock
