---
takel_ship_podman_deb_install_packages:
  - bash-completion
  - bat
  - curl
  - git
  - iproute2
  - jq
  - nano
  - skopeo
  - tree
  - vim
  - wget
  - yq

takel_ship_podman_user:
  owner: podman
  group: podman
  mode:
    dir: "0755"
    file: "0644"

takel_ship_podman_socket:
  path: /home/podman/.run/podman.sock
  socket: unix:///home/podman/.run/podman.sock
