---
takel_ship_podman_deb_install_packages:
  - curl
  - iproute2
  - jq
  - nano
  - skopeo
  - tmux
  - tree
  - vim
  - wget
  - yq

takel_ship_podman_user:
  owner: podman
  group: podman
  mode:
    dir: "0755"
    file: "0644"

