---
driver:
  name: docker
platforms:
  - name: molecule_default_${HOSTNAME:-name}
    image: ${TAKELAGE_PROJECT_BASE_IMG:-nobaseimage}
    command: ${TAKELAGE_PROJECT_COMMAND:-/usr/bin/tail -f /dev/null}
    pre_build_image: true
    privileged: true
    groups:
      - users
      - molecule
    published_ports:
      - 127.0.0.1:20022:22/tcp
      - 127.0.0.1:20080:80/tcp
      - 127.0.0.1:23000:3000/tcp
      - 127.0.0.1:25000:5000/tcp
provisioner:
  name: ansible
  playbooks:
    converge: >-
      ../../${TAKELAGE_MOLECULE_CONVERGE_PLAYBOOK:-playbook-site.yml}
  config_options:
    defaults:
      interpreter_python: auto_silent
      stdout_callback: yaml
      bin_ansible_callbacks: true
  inventory:
    links:
      group_vars: ../../group_vars/
verifier:
  name: testinfra
  options:
    v: true
  additional_files_or_dirs: ${TAKELAGE_MOLECULE_VERIFIER_FILES:-[]}
  env:
    PYTEST_ADDOPTS: '--color=yes'
dependency:
  enabled: false
scenario:
  create_sequence:
    - create
  converge_sequence:
    - create
    - converge
  destroy_sequence:
    - destroy
  test_sequence:
    - cleanup
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - verify
    - destroy
