---
- name: "(bashrc: {{ takel_user_name }}) copy .bashrc file"
  ansible.builtin.copy:
    src: bashrc
    dest: "{{ takel_user_home }}/.bashrc"
    owner: "{{ takel_user_name }}"
    group: "{{ takel_user_group }}"
    mode: "{{ takel_user_mode_file }}"

- name: "(bashrc: {{ takel_user_name }}) create .bashrc.d directory"
  ansible.builtin.file:
    dest: "{{ takel_user_home }}/.bashrc.d"
    state: directory
    owner: "{{ takel_user_name }}"
    group: "{{ takel_user_group }}"
    mode: "{{ takel_user_mode_dir }}"

- name: "(bashrc: {{ takel_user_name }}) copy .bashrc.d files"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ takel_user_home }}/.bashrc.d/{{ item }}"
    owner: "{{ takel_user_name }}"
    group: "{{ takel_user_group }}"
    mode: "{{ takel_user_mode_file }}"
  loop: "{{ takel_user_bashrc_d }}"
