---
- name: (main) include create
  ansible.builtin.include_tasks: create.yml
  when: takel_user_create
  tags: always

- name: (main) include bashrc
  ansible.builtin.include_tasks: bashrc.yml
  tags: always

- name: (main) include configure
  ansible.builtin.include_tasks: configure.yml
  tags: always
