---
- name: (compose) (dirs) create compose dir
  ansible.builtin.file:
    path: >-
      {{ takel_ship_compose_home_dir }}/{{
      takel_ship_compose_dist_dir }}/{{
      takel_ship_compose_compose_dir }}
    state: directory
    owner: "{{ takel_ship_podman_user.owner }}"
    group: "{{ takel_ship_podman_user.group }}"
    mode: "{{ takel_ship_podman_user.mode.dir }}"

- name: (compose) (dirs) create services dir
  ansible.builtin.file:
    path: >-
      {{ takel_ship_compose_home_dir }}/{{
      takel_ship_compose_dist_dir }}/{{
      takel_ship_compose_compose_dir }}/{{
      takel_ship_compose_services_dir }}
    state: directory
    owner: "{{ takel_ship_podman_user.owner }}"
    group: "{{ takel_ship_podman_user.group }}"
    mode: "{{ takel_ship_podman_user.mode.dir }}"

- name: (compose) (dirs) create compose projects dir
  ansible.builtin.file:
    path: >-
      {{ takel_ship_compose_home_dir }}/{{
      takel_ship_compose_dist_dir }}/{{
      takel_ship_compose_compose_dir }}/{{
      takel_ship_compose_projects_dir }}
    state: directory
    owner: "{{ takel_ship_podman_user.owner }}"
    group: "{{ takel_ship_podman_user.group }}"
    mode: "{{ takel_ship_podman_user.mode.dir }}"

- name: (compose) (dirs) create base projects dir
  ansible.builtin.file:
    path: >-
      {{ takel_ship_compose_home_dir }}/{{
      takel_ship_compose_dist_dir }}/{{
      takel_ship_compose_projects_dir }}
    state: directory
    owner: "{{ takel_ship_podman_user.owner }}"
    group: "{{ takel_ship_podman_user.group }}"
    mode: "{{ takel_ship_podman_user.mode.dir }}"

- name: (compose) (dirs) create service dirs
  ansible.builtin.file:
    path: >-
      {{ takel_ship_compose_home_dir }}/{{
      takel_ship_compose_dist_dir }}/{{
      takel_ship_compose_compose_dir }}/{{
      takel_ship_compose_services_dir }}/{{
      takel_ship_compose_service.name }}
    state: directory
    owner: "{{ takel_ship_podman_user.owner }}"
    group: "{{ takel_ship_podman_user.group }}"
    mode: "{{ takel_ship_podman_user.mode.dir }}"
  loop: "{{ takel_ship_compose_services }}"
  loop_control:
    loop_var: takel_ship_compose_service

- name: (compose) (dirs) create preinstall dirs
  ansible.builtin.file:
    path: >-
      {{ takel_ship_compose_home_dir }}/{{
      takel_ship_compose_dist_dir }}/{{
      takel_ship_compose_compose_dir }}/{{
      takel_ship_compose_services_dir }}/{{
      takel_ship_compose_service.name }}/{{
      takel_ship_compose_preinstall_dir }}
    state: directory
    owner: "{{ takel_ship_podman_user.owner }}"
    group: "{{ takel_ship_podman_user.group }}"
    mode: "{{ takel_ship_podman_user.mode.dir }}"
  loop: "{{ takel_ship_compose_services }}"
  loop_control:
    loop_var: takel_ship_compose_service

- name: (compose) (dirs) create postinstall dirs
  ansible.builtin.file:
    path: >-
      {{ takel_ship_compose_home_dir }}/{{
      takel_ship_compose_dist_dir }}/{{
      takel_ship_compose_compose_dir }}/{{
      takel_ship_compose_services_dir }}/{{
      takel_ship_compose_service.name }}/{{
      takel_ship_compose_postinstall_dir }}
    state: directory
    owner: "{{ takel_ship_podman_user.owner }}"
    group: "{{ takel_ship_podman_user.group }}"
    mode: "{{ takel_ship_podman_user.mode.dir }}"
  loop: "{{ takel_ship_compose_services }}"
  loop_control:
    loop_var: takel_ship_compose_service

- name: (compose) (dirs) create compose projects dirs
  ansible.builtin.file:
    path: >-
      {{ takel_ship_compose_home_dir }}/{{
      takel_ship_compose_dist_dir }}/{{
      takel_ship_compose_compose_dir }}/{{
      takel_ship_compose_projects_dir }}/{{
      takel_ship_compose_project.name }}
    state: directory
    owner: "{{ takel_ship_podman_user.owner }}"
    group: "{{ takel_ship_podman_user.group }}"
    mode: "{{ takel_ship_podman_user.mode.dir }}"
  loop: "{{ takel_ship_compose_projects }}"
  loop_control:
    loop_var: takel_ship_compose_project

- name: (compose) (dirs) create base projects dirs
  ansible.builtin.file:
    path: >-
      {{ takel_ship_compose_home_dir }}/{{
      takel_ship_compose_dist_dir }}/{{
      takel_ship_compose_projects_dir }}/{{
      takel_ship_compose_project.name }}
    state: directory
    owner: "{{ takel_ship_podman_user.owner }}"
    group: "{{ takel_ship_podman_user.group }}"
    mode: "{{ takel_ship_podman_user.mode.dir }}"
  loop: "{{ takel_ship_compose_projects }}"
  loop_control:
    loop_var: takel_ship_compose_project
