---
- name: (main) include install
  ansible.builtin.include_tasks: install.yml
  tags:
    - takel
    - takel_ships
    - takel_ship_compose_install

- name: (main) include compose dir
  ansible.builtin.include_tasks: compose/main.yml
  tags:
    - takel
    - takel_ships
    - takel_ship_compose_compose
