---
- name: (main) include localhost
  ansible.builtin.include_tasks: localhost.yml
  when: takel_ship_compose_create_local_compose_file is true
  tags:
    - takel
    - takel_ships
    - takel_ship_compose_localhost

- name: (main) include compose dir
  ansible.builtin.include_tasks: compose/main.yml
  tags:
    - takel
    - takel_ships
    - takel_ship_compose_compose
