---
- name: (compose) (main) include compose dirs
  ansible.builtin.include_tasks: dirs.yml
  tags: always

- name: (compose) (main) include compose services
  ansible.builtin.include_tasks: services.yml
  tags: always

- name: (compose) (main) include compose projects
  ansible.builtin.include_tasks: projects.yml
  tags: always
