---
# dist/compose/projects

- name: (compose) (projects) deploy compose file
  ansible.builtin.template:
    src: docker-compose.projects.yml.j2
    dest: >-
      {{ takel_ship_compose_home_dir }}/{{
      takel_ship_compose_dist_dir }}/{{
      takel_ship_compose_compose_dir }}/{{
      takel_ship_compose_projects_dir }}/{{
      takel_ship_compose_project.name }}/{{
      takel_ship_compose_docker_compose_yml }}
    owner: "{{ takel_ship_podman_user.owner }}"
    group: "{{ takel_ship_podman_user.group }}"
    mode: "{{ takel_ship_podman_user.mode.file }}"
  loop: "{{ takel_ship_compose_projects }}"
  loop_control:
    loop_var: takel_ship_compose_project

- name: (compose) (projects) deploy bash run docker down script
  ansible.builtin.template:
    src: run-docker-down.project.bash.j2
    dest: >-
      {{ takel_ship_compose_home_dir }}/{{
      takel_ship_compose_dist_dir }}/{{
      takel_ship_compose_compose_dir }}/{{
      takel_ship_compose_projects_dir }}/{{
      takel_ship_compose_project.name }}/{{
      takel_ship_compose_run_docker_down }}
    owner: "{{ takel_ship_podman_user.owner }}"
    group: "{{ takel_ship_podman_user.group }}"
    mode: "{{ takel_ship_podman_user.mode.dir }}"
  loop: "{{ takel_ship_compose_projects }}"
  loop_control:
    loop_var: takel_ship_compose_project

- name: (compose) (projects) deploy bash run docker up script
  ansible.builtin.template:
    src: run-docker-up.project.bash.j2
    dest: >-
      {{ takel_ship_compose_home_dir }}/{{
      takel_ship_compose_dist_dir }}/{{
      takel_ship_compose_compose_dir }}/{{
      takel_ship_compose_projects_dir }}/{{
      takel_ship_compose_project.name }}/{{
      takel_ship_compose_run_docker_up }}
    owner: "{{ takel_ship_podman_user.owner }}"
    group: "{{ takel_ship_podman_user.group }}"
    mode: "{{ takel_ship_podman_user.mode.dir }}"
  loop: "{{ takel_ship_compose_projects }}"
  loop_control:
    loop_var: takel_ship_compose_project

- name: (compose) (projects) deploy bash run podman down script
  ansible.builtin.template:
    src: run-podman-down.project.bash.j2
    dest: >-
      {{ takel_ship_compose_home_dir }}/{{
      takel_ship_compose_dist_dir }}/{{
      takel_ship_compose_compose_dir }}/{{
      takel_ship_compose_projects_dir }}/{{
      takel_ship_compose_project.name }}/{{
      takel_ship_compose_run_podman_down }}
    owner: "{{ takel_ship_podman_user.owner }}"
    group: "{{ takel_ship_podman_user.group }}"
    mode: "{{ takel_ship_podman_user.mode.dir }}"
  loop: "{{ takel_ship_compose_projects }}"
  loop_control:
    loop_var: takel_ship_compose_project

- name: (compose) (projects) deploy bash run podman up script
  ansible.builtin.template:
    src: run-podman-up.project.bash.j2
    dest: >-
      {{ takel_ship_compose_home_dir }}/{{
      takel_ship_compose_dist_dir }}/{{
      takel_ship_compose_compose_dir }}/{{
      takel_ship_compose_projects_dir }}/{{
      takel_ship_compose_project.name }}/{{
      takel_ship_compose_run_podman_up }}
    owner: "{{ takel_ship_podman_user.owner }}"
    group: "{{ takel_ship_podman_user.group }}"
    mode: "{{ takel_ship_podman_user.mode.dir }}"
  loop: "{{ takel_ship_compose_projects }}"
  loop_control:
    loop_var: takel_ship_compose_project

# dist/projects

- name: (compose) (projects) deploy bash copy images script
  ansible.builtin.template:
    src: project.copy-images.bash.j2
    dest: >-
      {{ takel_ship_compose_home_dir }}/{{
      takel_ship_compose_dist_dir }}/{{
      takel_ship_compose_projects_dir }}/{{
      takel_ship_compose_project.name }}/{{
      takel_ship_compose_copy_images }}
    owner: "{{ takel_ship_podman_user.owner }}"
    group: "{{ takel_ship_podman_user.group }}"
    mode: "{{ takel_ship_podman_user.mode.dir }}"
  loop: "{{ takel_ship_compose_projects }}"
  loop_control:
    loop_var: takel_ship_compose_project

- name: (compose) (projects) deploy bash copy project script
  ansible.builtin.template:
    src: project.copy-project.bash.j2
    dest: >-
      {{ takel_ship_compose_home_dir }}/{{
      takel_ship_compose_dist_dir }}/{{
      takel_ship_compose_projects_dir }}/{{
      takel_ship_compose_project.name }}/{{
      takel_ship_compose_copy_project }}
    owner: "{{ takel_ship_podman_user.owner }}"
    group: "{{ takel_ship_podman_user.group }}"
    mode: "{{ takel_ship_podman_user.mode.dir }}"
  loop: "{{ takel_ship_compose_projects }}"
  loop_control:
    loop_var: takel_ship_compose_project

- name: (compose) (projects) deploy bash podman logs script
  ansible.builtin.template:
    src: project.podman-logs.bash.j2
    dest: >-
      {{ takel_ship_compose_home_dir }}/{{
      takel_ship_compose_dist_dir }}/{{
      takel_ship_compose_projects_dir }}/{{
      takel_ship_compose_project.name }}/{{
      takel_ship_compose_podman_logs }}
    owner: "{{ takel_ship_podman_user.owner }}"
    group: "{{ takel_ship_podman_user.group }}"
    mode: "{{ takel_ship_podman_user.mode.dir }}"
  loop: "{{ takel_ship_compose_projects }}"
  loop_control:
    loop_var: takel_ship_compose_project

- name: (compose) (projects) deploy bash set ports script
  ansible.builtin.template:
    src: project.set-ports.bash.j2
    dest: >-
      {{ takel_ship_compose_home_dir }}/{{
      takel_ship_compose_dist_dir }}/{{
      takel_ship_compose_projects_dir }}/{{
      takel_ship_compose_project.name }}/{{
      takel_ship_compose_set_ports }}
    owner: "{{ takel_ship_podman_user.owner }}"
    group: "{{ takel_ship_podman_user.group }}"
    mode: "{{ takel_ship_podman_user.mode.dir }}"
  loop: "{{ takel_ship_compose_projects }}"
  loop_control:
    loop_var: takel_ship_compose_project
