---
- name: (main) include install
  ansible.builtin.include_tasks: install.yml
  tags:
    - takel
    - takel_ships
    - takel_ship_services_install

- name: (main) include compose dir
  ansible.builtin.include_tasks: compose/main.yml
  tags:
    - takel
    - takel_ships
    - takel_ship_services_compose
