---
takel_ship_compose_services_services: []

takel_ship_compose_scripts:
  - "{{ takel_ship_compose_script_containers }}"

### end of group_vars

# default vars for role unit test
takel_ship_compose_services:
  - "{{ takel_ship_compose_example_service }}"

takel_ship_compose_projects:
  - name: default
    services:
      - "{{ takel_ship_compose_example_service }}"

takel_ship_compose_example_service:
  name: example
  role: takel_ship_compose
  template: docker-compose.example.yml.j2
  images:
    - "{{ takel_ship_compose_example_image }}"

takel_ship_compose_example_image:
  name: alpine
  tag: latest
  alias: alpine

takel_ship_compose_deb_install_packages:
  - curl
  - iproute2
  - jq
  - nano
  - skopeo
  - tmux
  - tree
  - vim
  - wget
  - yq

takel_ship_compose_user:
  owner: podman
  group: podman

takel_ship_compose_script_containers:
  name: containers.conf
  role: takel_ship_compose
  template: containers.conf.j2
  owner: "{{ takel_ship_compose_user.owner }}"
  group: "{{ takel_ship_compose_user.group }}"
  mode: '0644'
  path: >-
    {{ takel_ship_compose_home_dir
    }}/.config/containers

takel_ship_compose_home_dir: >-
  /home/{{ takel_ship_compose_user.owner }}
takel_ship_compose_data_dir: data
takel_ship_compose_dist_dir: dist
takel_ship_compose_compose_dir: compose
takel_ship_compose_service_filename: docker-compose
takel_ship_compose_service_fileext: yml
