---
takel_ship_compose_scripts:
  - "{{ takel_ship_compose_script_containers }}"
  - "{{ takel_ship_compose_script_takelship_yml }}"
  - "{{ takel_ship_compose_script_takelship_docker_compose }}"

### end of group_vars

# default vars for role unit test
takel_ship_compose_services:
  - "{{ takel_ship_compose_example_service }}"

takel_ship_compose_projects:
  - name: default
    services:
      - "{{ takel_ship_compose_example_service }}"

takel_ship_compose_example_service:
  name: example
  role: takel_ship_compose
  template: docker-compose.example.yml.j2
  # nonroot: true means that the container thinks
  # it is run as podman user (uid: 1000)
  # nonroot: false means that the container thinks
  # it is run as root user (uid: 0)
  # default is nonroot: false
  nonroot: false
  images:
    - "{{ takel_ship_compose_example_image }}"

takel_ship_compose_example_image:
  name: alpine
  tag: latest
  alias: alpine

takel_ship_compose_env_docker: env-docker
takel_ship_compose_run_docker: run-docker
takel_ship_compose_run_podman: run-podman
takel_ship_compose_run_preinstall: run-preinstall
takel_ship_compose_run_postinstall: run-postinstall
takel_ship_compose_dockerfile: Dockerfile
takel_ship_compose_copy_image: copy-image
takel_ship_compose_copy_images: copy-images
takel_ship_compose_copy_project: copy-project

takel_ship_compose_script_containers:
  name: containers.conf
  role: takel_ship_compose
  template: containers.conf.j2
  owner: "{{ takel_ship_podman_user.owner }}"
  group: "{{ takel_ship_podman_user.group }}"
  mode: "{{ takel_ship_podman_user.mode.file }}"
  path: >-
    {{ takel_ship_compose_home_dir
    }}/.config/containers

takel_ship_compose_script_takelship_yml:
  name: takelship.yml
  role: takel_ship_compose
  template: takelship.yml.j2
  mode: "{{ takel_ship_scripts_root.mode.file }}"
  path: >-
    {{ takel_ship_compose_home_dir }}/{{
    takel_ship_compose_dist_dir }}/{{
    takel_ship_compose_compose_dir }}

takel_ship_compose_script_takelship_docker_compose:
  name: docker-compose.yml
  role: takel_ship_compose
  template: docker-compose.takelship.yml.j2
  mode: "{{ takel_ship_scripts_root.mode.file }}"
  path: >-
    {{ takel_ship_compose_home_dir }}/{{
    takel_ship_compose_dist_dir }}/{{
    takel_ship_compose_compose_dir }}/{{
    takel_ship_compose_projects_dir }}

takel_ship_compose_home_dir: >-
  /home/{{ takel_ship_podman_user.owner }}
takel_ship_compose_data_dir: takelship
takel_ship_compose_dist_dir: dist
takel_ship_compose_compose_dir: compose
takel_ship_compose_projects_dir: projects
takel_ship_compose_service_filename: docker-compose
takel_ship_compose_service_fileext: yml

takel_ship_compose_create_local_compose_file: true
