---
- name: (main) include install tasks
  ansible.builtin.include_tasks: install.yml
  tags: always

- name: (main) include configure tasks
  ansible.builtin.include_tasks: configure.yml
  tags: always
